name: Auto Merge Pull Request

on:
  pull_request:
    types: [opened, edited, synchronize, labeled]

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to v3

      - name: Auto-merge if conditions met
        uses: pascalgn/automerge-action@v0.16.4   # Update to the latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # This is the token GitHub automatically provides
          merge_method: merge  # This is a valid input for specifying how the PR should be merged
