name: Demo to create automatic PR
on:
  push:
    branches:
      - main
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code 
        uses: actions/checkout@v3
     
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
        
      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          number: ${{ steps.demo-1.outputs.pull-request-number}}
          merge-method: merge
          
      - name: Merge Pull request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          number: ${{ steps.demo-1.outputs.pull-request-number}}
          method: merge 
